// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.RepeatingFunction = (function() {
    RepeatingFunction.prototype.handle = null;

    function RepeatingFunction(frequency, immediate, callback) {
      this.resume = __bind(this.resume, this);
      this.pause = __bind(this.pause, this);
      this.frequency = frequency;
      this.callback = callback;
      if (immediate) {
        this.resume();
      }
    }

    RepeatingFunction.prototype.pause = function() {
      clearInterval(this.handle);
      return this.handle = null;
    };

    RepeatingFunction.prototype.resume = function() {
      return this.handle = setInterval(this.callback, this.frequency);
    };

    return RepeatingFunction;

  })();

}).call(this);
